# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Fabric'
 pod 'Alamofire', '4.6.0'
 pod 'CocoaLumberjack', '~> 3.4'
end
